### ISSUE TITLE
获取消息后无返回信息

### ISSUE THREAD

**Issue by ghost** [lt94/package-qqbot#1]
<img src="http://app.67cc.cn/view.php/f86cd9c7db6e7e27ef6b84a1a56a9de1.png"/>

**Comment by lovezm** [comment]
我也是这样 哈哈哈哈

**Comment by LeetaoGoooo** [comment]
我的锅，之前的代码把和好友聊天的功能去掉了，只加上了群组的～～现在都可以了

**Comment by lovezm** [comment]
可不可以不重启程序 不想每天扫码啊~

**Comment by LeetaoGoooo** [comment]
@lovezm 可以的～～你重开一个issue～我晚点修复一下
